# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "yugo-terraform-state"
    dynamodb_table = "terraform-state-lock-dynamo"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
