name: Test2 Workflow

on:
  push:
    paths:
      - 'test2/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo test step
        run: echo "This is test2"
