name: Test3 Workflow

on:
  push:
    paths:
      - 'test3/**'

jobs:
  test3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo test step
        run: echo "This is test3"

      - name: Fail step
        run: exit 1
